sudo: false
language: ruby
rvm: jruby-1.7.12
jdk: openjdk7

env:
  matrix:
  - RAKE_TASK=spec
  - RAKE_TASK=rubocop

matrix:
  allow_failures:
  - env: RAKE_TASK=rubocop

services:
  - redis

addons:
  postgresql: 9.3

before_script:
  - 'RAILS_ENV=test bundle exec rake db:create db:structure:load --trace'

script: ./build.sh

notifications:
  irc: "irc.freenode.org#travis"
